apiVersion: v1  
kind: Service 
metadata:
  name: result-service
  label:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetport: 80
      NodePort: 30005
  selector:
    name: result-app-pod
    app: demo-voting-app
